server:
  port: 9092

spring:
  application:
    name: participant-service

  datasource:
    url: jdbc:mysql://localhost:3306/participant_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


# ACTIVER EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true